<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["peliculas", "Atras"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Editar Pelicula
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "peliculas/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldNombrePelicula" class="col-sm-2 control-label">Id Pelicula</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_pelicula", "size" => 30, "class" => "form-control", "id" => "fieldNombrePelicula"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombrePelicula" class="col-sm-2 control-label">Nombre de Pelicula</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombre_pelicula", "size" => 30, "class" => "form-control", "id" => "fieldNombrePelicula"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAã±oPelicula" class="col-sm-2 control-label">Fecha de Pelicula</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fecha_pelicula", "type" => "date", "class" => "form-control", "id" => "fieldAã±oPelicula"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGeneroPelicula" class="col-sm-2 control-label">Genero de Pelicula</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["genero_pelicula", "size" => 30, "class" => "form-control", "id" => "fieldGeneroPelicula"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdDirector" class="col-sm-2 control-label">Director</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_director", "type" => "number", "class" => "form-control", "id" => "fieldIdDirector"]) ?>
    </div>
</div>


<?php //echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Modificar", "class" => "btn btn-success"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
