<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Buscar Peliculas
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["peliculas/new", "Ingresar Pelicula"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "peliculas/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdPelicula" class="col-sm-2 control-label">Id de Pelicula</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_pelicula", "type" => "number", "class" => "form-control", "id" => "fieldIdPelicula"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombrePelicula" class="col-sm-2 control-label">Nombre de Pelicula</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombre_pelicula", "size" => 30, "class" => "form-control", "id" => "fieldNombrePelicula"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAã±oPelicula" class="col-sm-2 control-label">Fecha de Pelicula</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fecha_pelicula", "type" => "date", "class" => "form-control", "id" => "fieldAã±oPelicula"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGeneroPelicula" class="col-sm-2 control-label">Genero de Pelicula</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["genero_pelicula", "size" => 30, "class" => "form-control", "id" => "fieldGeneroPelicula"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdDirector" class="col-sm-2 control-label">Director</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_director", "type" => "number", "class" => "form-control", "id" => "fieldIdDirector"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Buscar", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
