<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["peliculas/index", "Atras"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["peliculas/new", "Ingresar Pelicula"]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Listas de Pelicula</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id Pelicula</th>
            <th>Nombre de Pelicula</th>
            <th>Fecha de Pelicula</th>
            <th>Genero de Pelicula</th>
            <th>Director</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $pelicula): ?>
            <tr>
                <td><?php echo $pelicula->id_pelicula ?></td>
            <td><?php echo $pelicula->nombre_pelicula ?></td>
            <td><?php echo $pelicula->fecha_pelicula ?></td>
            <td><?php echo $pelicula->genero_pelicula ?></td>
            <td><?php echo $pelicula->id_director ?></td>

                <td><?php echo $this->tag->linkTo(["peliculas/edit/" . $pelicula->id_pelicula, "Editar"]); ?></td>
                <td><?php echo $this->tag->linkTo(["peliculas/delete/" . $pelicula->id_pelicula, "Eliminar"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("peliculas/search", "Primero") ?></li>
                <li><?php echo $this->tag->linkTo("peliculas/search?page=" . $page->before, "<<") ?></li>
                <li><?php echo $this->tag->linkTo("peliculas/search?page=" . $page->next, ">>") ?></li>
                <li><?php echo $this->tag->linkTo("peliculas/search?page=" . $page->last, "Ultimo") ?></li>
            </ul>
        </nav>
    </div>
</div>
