<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["actor", "Atras"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Ingresar Actor
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "actor/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldNombreActor" class="col-sm-2 control-label">Nombre de Actor</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombre_actor", "size" => 30, "class" => "form-control", "id" => "fieldNombreActor","placeholder"=>"Ingrese nombre actor","required"=>"true"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechaNacimiento" class="col-sm-2 control-label">Fecha de Nacimiento</label>
    <div class="col-sm-10">
        <?php echo $this->tag::dateField(["fecha_nacimiento", "type" => "date", "class" => "form-control", "id" => "fieldFechaNacimiento","placeholder"=>"Ingrese fecha de nacimiento","required"=>"true"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-success"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
