<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["director", "Atras"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Editar Director
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "director/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldNombreDirector" class="col-sm-2 control-label">Id Director</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_director", "size" => 30, "class" => "form-control", "id" => "fieldIdDirector"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombreDirector" class="col-sm-2 control-label">Nombre del Director</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombre_director", "size" => 30, "class" => "form-control", "id" => "fieldNombreDirector"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechaNacimiento" class="col-sm-2 control-label">Fecha de Nacimiento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fecha_nacimiento", "type" => "date", "class" => "form-control", "id" => "fieldFechaNacimiento"]) ?>
    </div>
</div>


<?php //echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Modificar", "class" => "btn btn-success"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
